# Use Node.js version 22.2.0 as base image for build stage
FROM node:22.2.0-alpine as build-stage

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Production stage: Serve using nginx
FROM nginx:stable-alpine as production-stage

# Copy build output from build-stage to nginx server
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Command to run nginx
CMD ["nginx", "-g", "daemon off;"]
